<a href="https://colab.research.google.com/github/MgarciaGraterol/Estudio-de-tiendas/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda1 = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon,tienda
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175,tienda_1
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359,tienda_1
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444,tienda_1
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250,tienda_1
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359,tienda_1

In [ ]:
# Agregamos columna de tienda
tienda1['tienda'] = 'tienda_1'
tienda2['tienda'] = 'tienda_2'
tienda3['tienda'] = 'tienda_3'
tienda4['tienda'] = 'tienda_4'

# Unir todos los datos
datos = pd.concat([tienda1, tienda2, tienda3, tienda4], ignore_index=True)

datos.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon,tienda
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175,tienda_1
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359,tienda_1
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444,tienda_1
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250,tienda_1
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359,tienda_1

#1. Análisis de facturación

In [ ]:
datos['facturacion'] = datos['Precio'] * datos['Cantidad de cuotas']
facturacion_tienda = datos.groupby('tienda')['facturacion'].sum().sort_values(ascending=False)
facturacion_tienda

tienda
tienda_1    3.422718e+09
tienda_2    3.337189e+09
tienda_3    3.243817e+09
tienda_4    3.098827e+09
Name: facturacion, dtype: float64

# 2. Ventas por categoría

In [ ]:
ventas_categoria = datos.groupby(['tienda', 'Categoría del Producto'])['Cantidad de cuotas'].sum().unstack()
ventas_categoria

Categoría del Producto,Artículos para el hogar,Deportes y diversión,Electrodomésticos,Electrónicos,Instrumentos musicales,Juguetes,Libros,Muebles
tienda,,,,,,,,
tienda_1,489,796,906,1341,573,872,520,1446
tienda_2,493,720,890,1333,659,876,611,1265
tienda_3,542,873,882,1262,580,937,517,1408
tienda_4,590,786,756,1293,500,921,591,1392

# 3. Calificación promedio de la tienda

In [ ]:
calificaciones = datos.groupby('tienda')['Calificación'].mean().round(2)
calificaciones

tienda
tienda_1    3.98
tienda_2    4.04
tienda_3    4.05
tienda_4    4.00
Name: Calificación, dtype: float64

# 4. Productos más y menos vendidos

In [ ]:
productos_mas_vendidos = datos.groupby('Producto')['Cantidad de cuotas'].sum().sort_values(ascending=False).head(5)
productos_menos_vendidos = datos.groupby('Producto')['Cantidad de cuotas'].sum().sort_values().head(5)

productos_mas_vendidos, productos_menos_vendidos

(Producto
 Secadora de ropa    649
 Mesa de noche       627
 Pandereta           625
 Bicicleta           614
 Iphone 15           611
 Name: Cantidad de cuotas, dtype: int64,
 Producto
 Smartwatch        432
 Set de vasos      435
 Celular ABXY      447
 Dinosaurio Rex    458
 Mesa de centro    469
 Name: Cantidad de cuotas, dtype: int64)

# 5. Envío promedio por tienda

In [ ]:
envio_promedio = datos.groupby('tienda')['Costo de envío'].mean().round(2)
envio_promedio

tienda
tienda_1    26018.61
tienda_2    25216.24
tienda_3    24805.68
tienda_4    23459.46
Name: Costo de envío, dtype: float64

In [ ]:
#Informe Ejecutivo
# La Tienda 1 lidera en facturación total y mantiene una calificación de cliente elevada.
# La Tienda 2 y la Tienda 3 tienen rendimientos intermedios con ventas sólidas en algunas categorías, aunque su costo de envío es relativamente alto.
# En contraste, la Tienda 4 muestra la menor facturación total, menores volúmenes de venta, y una calificación promedio inferior al resto, lo que sugiere una experiencia de cliente menos satisfactoria.
# Recomendación: Considerar cerrar o vender la Tienda 4 para enfocar recursos en unidades más rentables o explorar nuevos modelos de negocio.